-- ─────────────────────────────────────────────────────────────────────────────
-- Crear tabla de Fotos de Visita Técnica (evidencia fotográfica de la visita)
--
-- Ejecutar UNA sola vez en el SQL Editor de Supabase
-- (Dashboard -> SQL Editor -> New query).
--
-- Sigue las convenciones del esquema existente (igual que foto_instalacion):
--   * nombre de tabla en snake_case singular
--   * id serial + constraint <tabla>_pkey
--   * FKs nombradas <tabla>_<columna>_fkey
--   * activo boolean default true
--   * columnas de auditoría en PascalCase (entre comillas)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE public.foto_visita_tecnica (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,

  -- Visita técnica a la que pertenece la foto
  visita_tecnica_id integer NOT NULL,

  -- URL de Cloudinary
  url text NOT NULL,

  -- Clasificación: 'inicial' (antes) | 'final' (después)
  tipo character varying DEFAULT 'inicial',

  -- Convenciones del esquema
  activo boolean NOT NULL DEFAULT true,
  "FechaRegistro" timestamp with time zone NOT NULL DEFAULT now(),
  "UsuarioRegistro" character varying,
  "IpRegistro" character varying,
  "UsuarioModificacion" character varying,
  "FechaModificacion" timestamp with time zone,
  "IpModificacion" character varying,
  "UsuarioEliminacion" character varying,
  "FechaEliminacion" timestamp with time zone,
  "IpEliminacion" character varying,

  CONSTRAINT foto_visita_tecnica_pkey PRIMARY KEY (id),
  CONSTRAINT foto_visita_tecnica_visita_tecnica_id_fkey
    FOREIGN KEY (visita_tecnica_id) REFERENCES public.visita_tecnica(id)
);

-- Índice: la consulta principal es "fotos de una visita"
CREATE INDEX idx_foto_visita_tecnica_visita
  ON public.foto_visita_tecnica (visita_tecnica_id, tipo);

-- Verificación
select column_name, data_type
from information_schema.columns
where table_schema = 'public' and table_name = 'foto_visita_tecnica'
order by ordinal_position;
