-- ─────────────────────────────────────────────────────────────────────────────
-- Crear tabla de Notificaciones (centro de notificaciones in-app)
--
-- Ejecutar UNA sola vez en el SQL Editor de Supabase
-- (Dashboard -> SQL Editor -> New query).
--
-- Sigue las convenciones del esquema existente:
--   * nombre de tabla en snake_case singular
--   * id serial + constraint <tabla>_pkey
--   * FKs nombradas <tabla>_<columna>_fkey
--   * activo boolean default true
--   * columnas de auditoría en PascalCase (entre comillas)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE public.notificacion (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,

  -- Destinatario de la notificación
  usuario_id integer NOT NULL,

  -- Contenido
  titulo character varying NOT NULL,
  mensaje text NOT NULL,

  -- Tipo para el badge del frontend:
  -- 'aprobado' | 'pendiente' | 'programado' | 'completado' | 'info'
  tipo character varying NOT NULL DEFAULT 'info',

  -- Origen del evento, para poder navegar al registro desde la notificación:
  -- 'mantenimiento' | 'instalacion' | 'visita_tecnica' | 'contrato' | 'equipo' | 'empresa'
  origen character varying,
  referencia_id integer,

  -- Estado de lectura
  leida boolean NOT NULL DEFAULT false,
  fecha_leida timestamp with time zone,

  -- Convenciones del esquema
  activo boolean NOT NULL DEFAULT true,
  "FechaRegistro" timestamp with time zone NOT NULL DEFAULT now(),
  "UsuarioRegistro" character varying,
  "IpRegistro" character varying,
  "UsuarioModificacion" character varying,
  "FechaModificacion" timestamp with time zone,
  "IpModificacion" character varying,
  "UsuarioEliminacion" character varying,
  "FechaEliminacion" timestamp with time zone,
  "IpEliminacion" character varying,

  CONSTRAINT notificacion_pkey PRIMARY KEY (id),
  CONSTRAINT notificacion_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuario(id),
  CONSTRAINT notificacion_tipo_check CHECK (tipo IN ('aprobado', 'pendiente', 'programado', 'completado', 'info'))
);

-- Índices: la consulta principal siempre es "notificaciones de un usuario"
CREATE INDEX idx_notificacion_usuario
  ON public.notificacion (usuario_id, "FechaRegistro" DESC);

-- Índice parcial para el conteo de no leídas (badge del sidebar)
CREATE INDEX idx_notificacion_no_leidas
  ON public.notificacion (usuario_id)
  WHERE leida = false AND activo = true;

-- ─────────────────────────────────────────────────────────────────────────────
-- OPCIONAL: habilitar Supabase Realtime para que el frontend reciba la
-- "campana" al instante (mismo mecanismo que enable_realtime.sql)
-- ─────────────────────────────────────────────────────────────────────────────
alter publication supabase_realtime add table public.notificacion;

-- Verificación
select schemaname, tablename
from pg_publication_tables
where pubname = 'supabase_realtime' and tablename = 'notificacion';
