<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sismeing.Domain\Sismeing.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="EntitiesDTO\Operaciones\" />
    <Folder Include="Interfaz\Catalogo\" />
  </ItemGroup>

</Project>
