<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sismeing.Domain\Sismeing.Domain.csproj" />
    <ProjectReference Include="..\Sismeing.Infrestructura\Sismeing.Infrestructura.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RazorLight" Version="2.3.1" />
  </ItemGroup>

</Project>
